apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - name: dotnet-api
        image: othbel/dotnet-api:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
